default: &default
  adapter:  <%= ENV.fetch('MYSQL_ADAPTER')     { 'mysql2' } %>
  encoding: <%= ENV.fetch('MYSQL_ENCODING')    { 'utf8mb4' } %>
  pool:     <%= ENV.fetch('MYSQL_POOL')        { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER')        { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD')    { nil } %>
  host:     <%= ENV.fetch('MYSQL_HOST')        { '127.0.0.1' } %>
  port:     <%= ENV.fetch('MYSQL_PORT')        { 3306 } %>
  socket:   <%= ENV.fetch('MYSQL_SOCKET')      { '/tmp/mysql.sock' } %>

test:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') { 'harvester_test' } %>

development:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') { 'harvester_development' } %>

uat:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') { 'harvester_uat' } %>

staging:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') { 'harvester_staging' } %>

production:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') { 'harvester_production' } %>
